/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CaptureGroupPanel: typeof import('./views/captures/components/CaptureGroupPanel.vue')['default']
    DocumentDetailCard: typeof import('./views/document/components/DocumentDetailCard.vue')['default']
    DocumentPreviewCard: typeof import('./views/document/components/DocumentPreviewCard.vue')['default']
    DrawerRightPanel: typeof import('./views/exploration/components/DrawerRightPanel.vue')['default']
    DrawerSideCaptureGroup: typeof import('./views/captures/components/DrawerSideCaptureGroup.vue')['default']
    HomeView: typeof import('./views/home/components/HomeView.vue')['default']
    Iconify: typeof import('./components/ui/Iconify.vue')['default']
    ILucideAlertCircle: typeof import('~icons/lucide/alert-circle')['default']
    ILucideArrowLeft: typeof import('~icons/lucide/arrow-left')['default']
    ILucideArrowRight: typeof import('~icons/lucide/arrow-right')['default']
    ILucideArrowUpDown: typeof import('~icons/lucide/arrow-up-down')['default']
    ILucideBookOpen: typeof import('~icons/lucide/book-open')['default']
    ILucideCalendarDays: typeof import('~icons/lucide/calendar-days')['default']
    ILucideCamera: typeof import('~icons/lucide/camera')['default']
    ILucideCheck: typeof import('~icons/lucide/check')['default']
    ILucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    ILucideChevronLeft: typeof import('~icons/lucide/chevron-left')['default']
    ILucideChevronRight: typeof import('~icons/lucide/chevron-right')['default']
    ILucideChevronUp: typeof import('~icons/lucide/chevron-up')['default']
    ILucideClose: typeof import('~icons/lucide/close')['default']
    ILucideDownload: typeof import('~icons/lucide/download')['default']
    ILucideEllipsisVertical: typeof import('~icons/lucide/ellipsis-vertical')['default']
    ILucideExpand: typeof import('~icons/lucide/expand')['default']
    ILucideEye: typeof import('~icons/lucide/eye')['default']
    ILucideFileDown: typeof import('~icons/lucide/file-down')['default']
    ILucideFilePlus2: typeof import('~icons/lucide/file-plus2')['default']
    ILucideFileText: typeof import('~icons/lucide/file-text')['default']
    ILucideFolder: typeof import('~icons/lucide/folder')['default']
    ILucideFolderOpen: typeof import('~icons/lucide/folder-open')['default']
    ILucideFolderPlus: typeof import('~icons/lucide/folder-plus')['default']
    ILucideGrid2x2: typeof import('~icons/lucide/grid2x2')['default']
    ILucideHouse: typeof import('~icons/lucide/house')['default']
    ILucideImage: typeof import('~icons/lucide/image')['default']
    ILucideImagePlus: typeof import('~icons/lucide/image-plus')['default']
    ILucideImages: typeof import('~icons/lucide/images')['default']
    ILucideLayoutGrid: typeof import('~icons/lucide/layout-grid')['default']
    ILucideList: typeof import('~icons/lucide/list')['default']
    ILucideMenu: typeof import('~icons/lucide/menu')['default']
    ILucideMinus: typeof import('~icons/lucide/minus')['default']
    ILucideNotebookTabs: typeof import('~icons/lucide/notebook-tabs')['default']
    ILucidePencil: typeof import('~icons/lucide/pencil')['default']
    ILucidePlus: typeof import('~icons/lucide/plus')['default']
    ILucidePlusCircle: typeof import('~icons/lucide/plus-circle')['default']
    ILucideRedo2: typeof import('~icons/lucide/redo2')['default']
    ILucideRefreshCw: typeof import('~icons/lucide/refresh-cw')['default']
    ILucideSave: typeof import('~icons/lucide/save')['default']
    ILucideSearch: typeof import('~icons/lucide/search')['default']
    ILucideSettings2: typeof import('~icons/lucide/settings2')['default']
    ILucideSparkles: typeof import('~icons/lucide/sparkles')['default']
    ILucideTrash: typeof import('~icons/lucide/trash')['default']
    ILucideTrash2: typeof import('~icons/lucide/trash2')['default']
    ILucideUndo2: typeof import('~icons/lucide/undo2')['default']
    ILucideX: typeof import('~icons/lucide/x')['default']
    ModalAlert: typeof import('./components/ui/modal/ModalAlert.vue')['default']
    ModalBase: typeof import('./components/ui/modal/ModalBase.vue')['default']
    ModalCaptureFolderForm: typeof import('./views/document/components/ModalCaptureFolderForm.vue')['default']
    ModalCaptureImages: typeof import('./views/captures/components/ModalCaptureImages.vue')['default']
    ModalConfirm: typeof import('./components/ui/modal/ModalConfirm.vue')['default']
    ModalCreateProject: typeof import('./views/main/components/ModalCreateProject.vue')['default']
    PanelCaptureGroup: typeof import('./views/captures/components/PanelCaptureGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Versions: typeof import('./components/Versions.vue')['default']
  }
}
