/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CaptureGroupPanel: typeof import('./views/captures/components/CaptureGroupPanel.vue')['default']
    DrawerRightPanel: typeof import('./views/exploration/components/DrawerRightPanel.vue')['default']
    DrawerSideCaptureGroup: typeof import('./views/captures/components/DrawerSideCaptureGroup.vue')['default']
    Iconify: typeof import('./components/ui/Iconify.vue')['default']
    ILucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    ILucideChevronLeft: typeof import('~icons/lucide/chevron-left')['default']
    ILucideChevronRight: typeof import('~icons/lucide/chevron-right')['default']
    ILucideExpand: typeof import('~icons/lucide/expand')['default']
    ILucideMenu: typeof import('~icons/lucide/menu')['default']
    ILucidePlus: typeof import('~icons/lucide/plus')['default']
    ILucideRefreshCw: typeof import('~icons/lucide/refresh-cw')['default']
    ILucideTrash: typeof import('~icons/lucide/trash')['default']
    ILucideX: typeof import('~icons/lucide/x')['default']
    ModalAlert: typeof import('./components/ui/modal/ModalAlert.vue')['default']
    ModalBase: typeof import('./components/ui/modal/ModalBase.vue')['default']
    ModalCaptureImages: typeof import('./views/captures/components/ModalCaptureImages.vue')['default']
    ModalConfirm: typeof import('./components/ui/modal/ModalConfirm.vue')['default']
    PanelCaptureGroup: typeof import('./views/captures/components/PanelCaptureGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Versions: typeof import('./components/Versions.vue')['default']
  }
}
